import React from 'react';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './Components/nav-bar.jsx'
import FootBar from './Components/foot-bar.jsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" id ="container">
        {/* header */}
        {/* <header> */}
        {/* </header> */}

        {/* main body */}
          <body className={inter.className}>
      <div className="flex flex-col min-h-screen bg-gray-200">
            <header>
              <NavBar/>
            </header>
              <main>
              {children}
              </main>
          <footer>
          <FootBar/>
          </footer>
      </div>
          </body>

        {/* footer */}
    </html>
  )
}
